"""Page 2 — Game Props: every player's full milestone ladder for a chosen game."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import _shared as sh
import pandas as pd
import streamlit as st

st.set_page_config(page_title="AFL Predictor — Props", page_icon="🎯", layout="wide")
st.title("🎯 Game Props")
st.caption("Every integer milestone (9+, 10+, …) for every player in a game, with "
           "the model's chance of hitting and SportsBet's odds where posted.")

events = sh.upcoming_events()
if events.empty:
    st.warning("No upcoming AFL games from the odds feed right now.")
    st.stop()

labels = {f"{r['home_team']} v {r['away_team']}  ·  "
          f"{pd.to_datetime(r['commence_time']).strftime('%a %d %b')}": r
          for _, r in events.iterrows()}
choice = st.selectbox("Select a game", list(labels))
ev = labels[choice]
home, away = ev["home_team"], ev["away_team"]
venue, when = sh.fixture_venues(2026).get((home, away), ("", None))

ladders = sh.game_prop_ladders(ev["id"], home, away, venue, when)
if ladders.empty:
    st.warning("No player markets available for this game yet.")
    st.stop()

stat = st.radio("Stat", sh.RATED, horizontal=True,
                format_func=str.capitalize)
view = st.radio("Show", ["Model probability", "SportsBet odds"], horizontal=True)

sub = ladders[ladders["stat"] == stat].copy()
players = st.multiselect("Filter players (optional)",
                         sorted(sub["player"].unique()))
if players:
    sub = sub[sub["player"].isin(players)]
if sub.empty:
    st.info("No lines for this selection.")
    st.stop()

# Order milestone columns numerically (9+, 10+, 11+ … not lexically).
sub["m"] = sub["milestone"].str.rstrip("+").astype(int)
order = [f"{m}+" for m in sorted(sub["m"].unique())]

value_col = "model_p" if view.startswith("Model") else "sb_odds"
pivot = sub.pivot_table(index="player", columns="milestone", values=value_col,
                        aggfunc="first").reindex(columns=order)
team_of = sub.groupby("player")["team"].first()
pivot.insert(0, "team", team_of)

val_cols = [c for c in pivot.columns if c != "team"]
if view.startswith("Model"):
    st.caption("Model probability the player reaches each milestone. "
               "Greener = more likely.")

    def _grad(v):
        # red (0) -> yellow (0.5) -> green (1), no matplotlib needed.
        if pd.isna(v):
            return ""
        v = max(0.0, min(1.0, float(v)))
        if v < 0.5:
            r, g = 235, int(120 + 115 * (v / 0.5))
        else:
            r, g = int(235 - 150 * ((v - 0.5) / 0.5)), 235
        return f"background-color: rgba({r},{g},90,0.55)"

    sty = (pivot.style
           .map(_grad, subset=val_cols)
           .format({c: "{:.0%}" for c in val_cols}, na_rep="·"))
else:
    st.caption("SportsBet decimal odds (blank where SportsBet doesn't post that line).")
    sty = pivot.style.format({c: "{:.2f}" for c in val_cols}, na_rep="·")

st.dataframe(sty, use_container_width=True, height=min(70 + 35 * len(pivot), 800))

with st.expander("What am I looking at?"):
    st.markdown(
        "- Each cell is **P(player gets that many or more)** of the selected stat, "
        "from the calibrated projection (recent form + opponent/venue/weather).\n"
        "- Disposal milestones come straight from SportsBet's `X+` ladder; goals "
        "and tackles ladders are generated by the model (SportsBet posts fewer of "
        "these).\n"
        "- Switch to **SportsBet odds** to compare the model's probability against "
        "the price (implied % ≈ 1 ÷ odds)." )
