"""Same Game Multi (SGM) builder.

Given the "X+" milestone legs SportsBet posts for a fixture, attach our
calibrated model probability to each, then find the **safest** combination that
reaches a target multiplier (2x / 3x / 5x / 10x).

Maths
-----
For legs combined in a multi the combined decimal odds are the product of the
leg odds, and (treating legs as independent) the chance the whole multi lands is
the product of the leg probabilities. So for a target multiplier ``M`` the
safest multi solves:

    maximise   Π p_i          (joint probability of all legs landing)
    subject to Π o_i >= M      (combined odds clear the target)
               one leg per player, 2..max_legs legs

In log space this is a grouped knapsack (each player is a group from which we
pick at most one leg); we solve it exactly with a small DP over bucketed
log-odds. Maximising Π p_i directly is what "safest" means — and because
overshooting the odds target lowers Π p_i, the solver naturally lands as close
to ``M`` as the available lines allow.

Caveats (surfaced to the user):
  * SportsBet prices its actual SGM with correlation adjustments, so the real
    payout differs from the product of legs (usually a little shorter). We keep
    legs to *different players* to keep that gap and the independence assumption
    small; mild positive in-game correlation makes the true joint probability a
    touch higher than estimated, i.e. slightly safer.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pandas as pd

from ..model import player_props
from ..model import position_adjustment as _pos_adj
from ..model import tactical as _tactical
from ..model import leg_calibration as _leg_cal

# ---------------------------------------------------------------------------
# Volatility guard — players with high game-to-game variance hurt parlays.
# Generated by scripts/player_volatility.py after each round.
# ---------------------------------------------------------------------------
_VOL_PATH = Path(__file__).parent.parent.parent / "api" / "data" / "player_volatility.json"
_VOL_CACHE: dict | None = None

def _load_volatility() -> dict:
    """Return {player: entry}. Handles both the flat legacy format and the
    current {"updated": ..., "players": [...]} list format."""
    global _VOL_CACHE
    if _VOL_CACHE is None:
        try:
            raw = json.loads(_VOL_PATH.read_text())
            if isinstance(raw.get("players"), list):
                _VOL_CACHE = {p.get("player"): p for p in raw["players"]}
            else:
                _VOL_CACHE = raw
        except Exception:
            _VOL_CACHE = {}
    return _VOL_CACHE

def is_volatile(player_scraped: str) -> bool:
    """True if the player's disposal CV > 0.35 — exclude from parlays."""
    entry = _load_volatility().get(player_scraped)
    return bool(entry and entry.get("parlay_flag", False))


def attach_model_probs(legs: pd.DataFrame, player_stats: pd.DataFrame, elos: dict,
                       *, venue: str | None, forecast: dict | None,
                       home: str, away: str, min_games: int = 8,
                       exp_margin: float | None = None) -> pd.DataFrame:
    """Add the model's P(leg lands) to each milestone leg."""
    index = player_props.build_player_index(player_stats)
    pos_table = _pos_adj.get_table(player_stats)
    tact_ctx = _tactical.build_context(player_stats, home=home, away=away,
                                       legs=legs, exp_margin=exp_margin)
    out = []
    cache: dict[tuple, float] = {}
    for _, o in legs.iterrows():
        scraped = player_props.resolve_player(o["player"], index)
        if scraped is None:
            continue
        if is_volatile(scraped):
            continue
        ph = player_stats[player_stats["player"] == scraped]
        if len(ph) < min_games:
            continue
        is_home = ph.sort_values("date")["team"].iloc[-1] == home
        opponent = away if is_home else home
        key = (scraped, o["stat"])
        if key not in cache:
            cache[key] = player_props.project(
                player_stats, scraped, o["stat"], opponent, is_home,
                elo=elos.get(o["stat"]), venue=venue, forecast=forecast,
                position_table=pos_table, tactical=tact_ctx)
        proj = cache[key]
        raw_p = float(proj.prob_over(o["line"]))
        price = float(o["price"])
        # Empirically calibrated hit probability (see model.leg_calibration):
        # the raw model is overconfident on the legs it selects, so `prob` —
        # used for selection, display and joint probabilities — is corrected
        # against settled results before anything consumes it.
        out.append({**o.to_dict(), "player_scraped": scraped,
                    "prob": _leg_cal.calibrate(raw_p, price),
                    "prob_raw": raw_p,
                    "odds": price,
                    # Projection parameters for Monte Carlo game simulation
                    "proj_mean": float(proj.mean), "proj_sd": float(proj.sd),
                    "proj_dist": proj.dist,
                    "sim_team": home if is_home else away})
    return pd.DataFrame(out)


# Per-leg risk discount used ONLY for ranking combos inside safest_multi.
# Each leg multiplies the ranking score by this factor on top of its model
# probability, pricing in what the independence assumption misses: per-leg
# model error compounds, and any player can miss through injury/role surprise.
# An extra leg must therefore improve the true joint probability by more than
# ~1.5% to be worth adding — this is the cost/benefit weight on leg count.
# Raised from 0.985 after the R19 post-mortem: settled multis under-performed
# their claimed joint probability at every leg count (actual/claimed ratio
# 0.35-0.83), i.e. per-leg errors compound worse than independence implies.
# Most of that is now handled by leg_calibration; this keeps a residual
# penalty so an extra leg must add ~3% to earn its place.
LEG_RISK_DISCOUNT = 0.97

# Market-blend shrinkage, ranking-only. NOW 0.0 BY DESIGN: leg ``prob`` is
# already the calibrated probability from model.leg_calibration, which folds
# in the market logit (~0.53 weight) and the overconfidence correction.
# Blending again here would double-count the book.
MARKET_BLEND = 0.0


def _rank_logp(leg: dict) -> float:
    """Log of the ranking probability: model prob shrunk toward book-implied."""
    p_model = leg["prob"]
    p_book = 1.0 / leg["odds"]
    return (1.0 - MARKET_BLEND) * math.log(p_model) + MARKET_BLEND * math.log(p_book)


def safest_multi(legs: pd.DataFrame, target: float, *, max_legs: int | None = None,
                 prob_floor: float = 0.30, prob_cap: float = 0.97,
                 odds_floor: float = 1.05, res: float = 0.025,
                 max_per_stat: int | None = None) -> dict | None:
    """Return the safest leg combination with combined odds >= ``target``.

    Exact grouped knapsack over bucketed log-odds: maximise the (leg-count
    discounted) joint probability subject to the combined odds clearing the
    target. With combined odds pinned at the target, maximising joint
    probability is the same as maximising edge (joint P minus book-implied P).

    ``legs`` must carry ``player_scraped``, ``odds`` and ``prob``. Returns a dict
    with the chosen legs, combined odds, joint probability and edge, or None.
    ``max_legs=None`` means unlimited — the LEG_RISK_DISCOUNT decides when an
    extra leg stops paying for itself. ``max_per_stat`` caps how many legs may
    share a stat (e.g. 2) to force diversification and cut the in-game
    correlation between same-stat legs.
    """
    if legs.empty:
        return None
    # Pool: meaningful, reachable legs; cap odds below target so no single leg
    # reaches it (guarantees a genuine multi of >= 2 legs).
    pool = legs[(legs["prob"] >= prob_floor) & (legs["prob"] <= prob_cap)
                & (legs["odds"] >= odds_floor) & (legs["odds"] <= target * 0.92)]
    if pool.empty:
        return None

    T = math.log(target)
    leg_cost = math.log(LEG_RISK_DISCOUNT)
    # dp: bucket(log-odds in [0,T)) -> (best discounted sum_log_prob, legs list)
    dp: dict[int, tuple[float, list]] = {0: (0.0, [])}
    reached: tuple[float, list] | None = None

    for _player, grp in pool.groupby("player_scraped"):
        options = grp.to_dict("records")
        new_dp = dict(dp)
        for b, (slp, llist) in dp.items():
            if max_legs is not None and len(llist) >= max_legs:
                continue
            cur = b * res
            for leg in options:
                if max_per_stat is not None and sum(
                        1 for x in llist if x["stat"] == leg["stat"]) >= max_per_stat:
                    continue
                no = cur + math.log(leg["odds"])
                nlp = slp + _rank_logp(leg) + leg_cost
                nlist = llist + [leg]
                if no >= T:
                    if len(nlist) >= 2 and (reached is None or nlp > reached[0]):
                        reached = (nlp, nlist)
                else:
                    nb = int(round(no / res))
                    if nb not in new_dp or nlp > new_dp[nb][0]:
                        new_dp[nb] = (nlp, nlist)
        dp = new_dp

    if reached is None:
        return None
    _, llist = reached
    odds = float(np.prod([leg["odds"] for leg in llist]))
    joint_indep = float(np.prod([leg["prob"] for leg in llist]))
    # Correlation-aware joint probability from 10,000 simulated games
    # (Gaussian copula, measured within-game correlations; falls back to the
    # independence product when projection parameters are unavailable).
    joint = _simulated_joint(llist)
    if joint is None:
        joint = joint_indep
    return {
        "target": target,
        "legs": sorted(llist, key=lambda leg: leg["prob"], reverse=True),
        "combined_odds": odds,
        "joint_prob": joint,
        "joint_prob_indep": joint_indep,
        "implied_prob": 1.0 / odds,
        "edge": joint - 1.0 / odds,
        "n_legs": len(llist),
    }


def _simulated_joint(legs: list[dict]) -> float | None:
    """Joint P(all legs hit) from Monte Carlo game simulation, or None."""
    needed = {"proj_mean", "proj_sd", "proj_dist", "sim_team", "line"}

    def _missing(v) -> bool:
        # pandas turns None into NaN when a frame gains a float column, so a
        # plain `is None` check silently lets NaN projections into the sim.
        return v is None or (isinstance(v, float) and math.isnan(v))

    if not legs or any(not needed <= set(l.keys()) or _missing(l.get("proj_mean"))
                       or _missing(l.get("proj_sd")) or not l.get("proj_dist")
                       for l in legs):
        return None
    from ..model import simulate
    players = [{"key": f"{l['player_scraped']}|{l['stat']}",
                "mean": l["proj_mean"], "sd": l["proj_sd"],
                "dist": l["proj_dist"], "team": l["sim_team"]}
               for l in legs]
    sims = simulate.simulate_game(players)
    joint_sim = simulate.joint_probability(
        sims, [{"key": f"{l['player_scraped']}|{l['stat']}",
                "line": l["line"]} for l in legs])
    if joint_sim is None:
        return None
    # The simulation's marginals are the RAW model distributions, but the legs
    # carry empirically calibrated probabilities. Keep the correlation
    # structure the sim measured and re-base it on the calibrated marginals:
    #   correlation factor = joint_sim / prod(raw_p)
    #   calibrated joint   = correlation factor * prod(calibrated_p)
    raw_prod = 1.0
    cal_prod = 1.0
    for l in legs:
        raw_prod *= float(l.get("prob_raw") or l["prob"])
        cal_prod *= float(l["prob"])
    if raw_prod <= 0:
        return joint_sim
    return float(min(1.0, (joint_sim / raw_prod) * cal_prod))


def build_for_targets(legs_with_probs: pd.DataFrame,
                      targets=(2, 3, 5, 10), **kwargs) -> dict:
    """Safest multi for each target multiplier."""
    return {t: safest_multi(legs_with_probs, float(t), **kwargs) for t in targets}

