/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectionsRouteImport } from './routes/projections'
import { Route as PremiershipWindowRouteImport } from './routes/premiership-window'
import { Route as MultiBuilderRouteImport } from './routes/multi-builder'
import { Route as LadderRouteImport } from './routes/ladder'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameEventIdRouteImport } from './routes/game.$eventId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionsRoute = ProjectionsRouteImport.update({
  id: '/projections',
  path: '/projections',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiershipWindowRoute = PremiershipWindowRouteImport.update({
  id: '/premiership-window',
  path: '/premiership-window',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiBuilderRoute = MultiBuilderRouteImport.update({
  id: '/multi-builder',
  path: '/multi-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const LadderRoute = LadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameEventIdRoute = GameEventIdRouteImport.update({
  id: '/game/$eventId',
  path: '/game/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/ladder': typeof LadderRoute
  '/multi-builder': typeof MultiBuilderRoute
  '/premiership-window': typeof PremiershipWindowRoute
  '/projections': typeof ProjectionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/game/$eventId': typeof GameEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/ladder': typeof LadderRoute
  '/multi-builder': typeof MultiBuilderRoute
  '/premiership-window': typeof PremiershipWindowRoute
  '/projections': typeof ProjectionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/game/$eventId': typeof GameEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/ladder': typeof LadderRoute
  '/multi-builder': typeof MultiBuilderRoute
  '/premiership-window': typeof PremiershipWindowRoute
  '/projections': typeof ProjectionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stats': typeof StatsRoute
  '/game/$eventId': typeof GameEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/ladder'
    | '/multi-builder'
    | '/premiership-window'
    | '/projections'
    | '/sitemap.xml'
    | '/stats'
    | '/game/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/ladder'
    | '/multi-builder'
    | '/premiership-window'
    | '/projections'
    | '/sitemap.xml'
    | '/stats'
    | '/game/$eventId'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/ladder'
    | '/multi-builder'
    | '/premiership-window'
    | '/projections'
    | '/sitemap.xml'
    | '/stats'
    | '/game/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  LadderRoute: typeof LadderRoute
  MultiBuilderRoute: typeof MultiBuilderRoute
  PremiershipWindowRoute: typeof PremiershipWindowRoute
  ProjectionsRoute: typeof ProjectionsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatsRoute: typeof StatsRoute
  GameEventIdRoute: typeof GameEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projections': {
      id: '/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof ProjectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premiership-window': {
      id: '/premiership-window'
      path: '/premiership-window'
      fullPath: '/premiership-window'
      preLoaderRoute: typeof PremiershipWindowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-builder': {
      id: '/multi-builder'
      path: '/multi-builder'
      fullPath: '/multi-builder'
      preLoaderRoute: typeof MultiBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladder': {
      id: '/ladder'
      path: '/ladder'
      fullPath: '/ladder'
      preLoaderRoute: typeof LadderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$eventId': {
      id: '/game/$eventId'
      path: '/game/$eventId'
      fullPath: '/game/$eventId'
      preLoaderRoute: typeof GameEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  LadderRoute: LadderRoute,
  MultiBuilderRoute: MultiBuilderRoute,
  PremiershipWindowRoute: PremiershipWindowRoute,
  ProjectionsRoute: ProjectionsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatsRoute: StatsRoute,
  GameEventIdRoute: GameEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
